# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='sender_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([('sender', 'receiver')]),
        ),
    ]
