# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20161026_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='receiver_state',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='sender_state',
        ),
    ]
