# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '\u0424\u043e\u0442\u043e', 'verbose_name_plural': '\u0424\u043e\u0442\u043e'},
        ),
    ]
