# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import usermedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0002_auto_20161129_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=usermedia.models.upload_photos, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
