# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import useractivities.models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0002_auto_20161226_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, upload_to=useractivities.models.upload_attachments),
        ),
    ]
