# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0003_auto_20161129_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at'], 'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e'),
            preserve_default=False,
        ),
    ]
