# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0004_auto_20161129_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='user',
        ),
    ]
