# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0003_extuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='friends',
            field=models.ManyToManyField(related_name='_extuser_friends_+', through='friendship.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
