# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0003_auto_20161026_1124'),
        ('extuser', '0004_auto_20161026_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='extuser',
            name='friendships',
            field=models.ManyToManyField(related_name='_extuser_friendships_+', through='friendship.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
